### ISSUE TITLE
Accessing axis variable values for multi-config builds is broken

### ISSUE THREAD

**Issue by midopa** [ikedam/groovy-label-assignment#2]
Jenkins 3.0
Groovy label plugin: 1.2.0

I have a multi-config project and I'm trying to use the plugin to assign a dynamic label based on each build configuration.

Example:
Axis "OS" with values "iOS" and "Android"

Based on the documentation, I expect the OS to be available in:
```
return binding.getVariables().get("OS");
```

But that returns null.

Any advice?

**Comment by midopa** [comment]
Found out what was going on.

So a Matrix Configuration build starts with the parent and then enumerates each configuration as a child.

So if I make sure the `currentJob` is a child configuration, then the axis variables are bound:
```
if (binding.currentJob instanceof hudson.matrix.MatrixConfiguration) {
    return binding.getVariables().get("OS");
}
```

I think this should be added to the documentation. Also: Maybe there's a cleaner way to do this check?

**Comment by ikedam** [comment]
I can't get what you mean...
You meant OS returned null on the parent, and valid values for chindren, didn't you?
What do you want?

**Comment by midopa** [comment]
I want to get an axis value for each configuration build so I can configure the label. The documentation says:

`return binding.getVariables().get("OS");`

But my labels have prefixes so I have to concatenate them in the Groovy script:

`return "label_" + binding.getVariables().get("OS");`

This gets stuck because a `MatrixProject` is run first and *then* each `MatrixConfiguration` build runs. The `MatrixProject` doesn't have any axis values bound. So the Groovy script returns `label_null` the first time and then waits for a node with `label_null`.

So I had to add that instance check to only run the Groovy script when a configuration build is running.

1. Is there a simpler way to do this?
1. If not, can the documentation be updated to note this behavior/sequence?

**Comment by ikedam** [comment]
Just add nulll check.
No plan to update the documentation.
